Two things changed: 1.Make this branch with the trunk version 47488 and also make my previous changes in it 2.Make GetSelection work and modify some of ItemAdded and ItemDeleted
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/branches/SOC2007_DVC@47489 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/distrib/mac/pbsetup-sh b/distrib/mac/pbsetup-sh
--- a/distrib/mac/pbsetup-sh
+++ b/distrib/mac/pbsetup-sh
@@ -49,10 +49,13 @@ if [ "${1}/../include/wx/mac/setup0.h" -nt "${1}/../include/wx/mac/setup.h" ] ; 
     echo "${0}:${LINENO}: warning: edit or replace \"include/wx/mac/setup.h\" to integrate changes"
 fi
 #
-# Copy setup.h to setup.h if setup.h doesn't exist
+# Copy user setup.h to build setup.h if the latter doesn't exist or is older
 #
-cp "${1}/../include/wx/mac/setup.h" "${2}/include/wx/setup.h"
-if [ ! -f "${2}/include/wx/setup.h" ] ; then
-    echo "${0}:${LINENO}: error: unable to create target setup file \"${2}/include/wx/setup.h\""
-    exit 1
+if [ ! -f "${2}/include/wx/setup.h" -o \
+     "${1}/../include/wx/mac/setup.h" -nt "${2}/include/wx/setup.h" ] ; then 
+    cp "${1}/../include/wx/mac/setup.h" "${2}/include/wx/setup.h"
+    if [ ! -f "${2}/include/wx/setup.h" ] ; then
+        echo "${0}:${LINENO}: error: unable to create target setup file \"${2}/include/wx/setup.h\""
+        exit 1
+    fi
 fi
