added checks to prevent running sub configure scripts directly (they can only be executed by the top level configure)
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/trunk@18752 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/contrib/configure b/contrib/configure
--- a/contrib/configure
+++ b/contrib/configure
@@ -523,11 +523,15 @@ fi
 
 
 
+if test "x$wx_cv_path_ifs" = "x"; then
+    { echo "configure: error: Please run configure from the top level directory." 1>&2; exit 1; }
+fi
+
 
 
 ESD_LINK=
 echo $ac_n "checking how to run the C preprocessor""... $ac_c" 1>&6
-echo "configure:531: checking how to run the C preprocessor" >&5
+echo "configure:535: checking how to run the C preprocessor" >&5
 # On Suns, sometimes $CPP names a directory.
 if test -n "$CPP" && test -d "$CPP"; then
   CPP=
@@ -542,13 +546,13 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 546 "configure"
+#line 550 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:552: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:556: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -559,13 +563,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 563 "configure"
+#line 567 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:569: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:573: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -576,13 +580,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -nologo -E"
   cat > conftest.$ac_ext <<EOF
-#line 580 "configure"
+#line 584 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:586: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:590: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -608,17 +612,17 @@ echo "$ac_t""$CPP" 1>&6
 
 ac_safe=`echo "esd.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for esd.h""... $ac_c" 1>&6
-echo "configure:612: checking for esd.h" >&5
+echo "configure:616: checking for esd.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 617 "configure"
+#line 621 "configure"
 #include "confdefs.h"
 #include <esd.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:622: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:626: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -636,7 +640,7 @@ if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
   echo "$ac_t""yes" 1>&6
   
   echo $ac_n "checking for esd_close in -lesd""... $ac_c" 1>&6
-echo "configure:640: checking for esd_close in -lesd" >&5
+echo "configure:644: checking for esd_close in -lesd" >&5
 ac_lib_var=`echo esd'_'esd_close | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -644,7 +648,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lesd  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 648 "configure"
+#line 652 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -655,7 +659,7 @@ int main() {
 esd_close()
 ; return 0; }
 EOF
-if { (eval echo configure:659: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:663: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
diff --git a/demos/configure b/demos/configure
--- a/demos/configure
+++ b/demos/configure
@@ -523,6 +523,10 @@ fi
 
 
 
+if test "x$wx_cv_if_gnu_make" = "x"; then
+    { echo "configure: error: Please run configure from the top level directory." 1>&2; exit 1; }
+fi
+
 IF_GNU_MAKE=$wx_cv_if_gnu_make
 
 
diff --git a/utils/configure b/utils/configure
--- a/utils/configure
+++ b/utils/configure
@@ -523,6 +523,10 @@ fi
 
 
 
+if test "x$wx_cv_path_glcanvas" = "x"; then
+    { echo "configure: error: Please run configure from the top level directory." 1>&2; exit 1; }
+fi
+
 GL_TOOLKIT_DIR=$wx_cv_path_glcanvas
 USE_GUI=$wx_cv_use_gui
 USE_RESOURCES=$wx_cv_use_resources
