regenerated after wxColour/File/Dir/FontPickerCtrl changes
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/trunk@39499 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -978,10 +978,14 @@ Optional Features:
   --enable-checklst       use wxCheckListBox (listbox with checkboxes) class
   --enable-choice         use wxChoice class
   --enable-choicebook     use wxChoicebook class
+  --enable-colourpicker   use wxColourPickerCtrl class
   --enable-combobox       use wxComboBox class
   --enable-comboctrl      use wxComboCtrl class
   --enable-datepick       use wxDatePickerCtrl class
+  --enable-dirpicker      use wxDirPickerCtrl class
   --enable-display        use wxDisplay class
+  --enable-filepicker     use wxFilePickerCtrl class
+  --enable-fontpicker     use wxFontPickerCtrl class
   --enable-gauge          use wxGauge class
   --enable-grid           use wxGrid class
   --enable-dataviewctrl,  use wxDataViewCtrl class
@@ -2198,10 +2202,14 @@ if test $DEBUG_CONFIGURE = 1; then
   DEFAULT_wxUSE_CHECKLST=no
   DEFAULT_wxUSE_CHOICE=no
   DEFAULT_wxUSE_CHOICEBOOK=no
+  DEFAULT_wxUSE_COLOURPICKERCTRL=no
   DEFAULT_wxUSE_COMBOBOX=no
   DEFAULT_wxUSE_COMBOCTRL=no
   DEFAULT_wxUSE_DATEPICKCTRL=no
   DEFAULT_wxUSE_DISPLAY=no
+  DEFAULT_wxUSE_DIRPICKERCTRL=no
+  DEFAULT_wxUSE_FILEPICKERCTRL=no
+  DEFAULT_wxUSE_FONTPICKERCTRL=no
   DEFAULT_wxUSE_GAUGE=no
   DEFAULT_wxUSE_GRID=no
   DEFAULT_wxUSE_HYPERLINKCTRL=no
@@ -2405,10 +2413,14 @@ else
   DEFAULT_wxUSE_CHECKLST=yes
   DEFAULT_wxUSE_CHOICE=yes
   DEFAULT_wxUSE_CHOICEBOOK=yes
+  DEFAULT_wxUSE_COLOURPICKERCTRL=yes
   DEFAULT_wxUSE_COMBOBOX=yes
   DEFAULT_wxUSE_COMBOCTRL=yes
   DEFAULT_wxUSE_DATEPICKCTRL=yes
   DEFAULT_wxUSE_DISPLAY=yes
+  DEFAULT_wxUSE_DIRPICKERCTRL=yes
+  DEFAULT_wxUSE_FILEPICKERCTRL=yes
+  DEFAULT_wxUSE_FONTPICKERCTRL=yes
   DEFAULT_wxUSE_GAUGE=yes
   DEFAULT_wxUSE_GRID=yes
   DEFAULT_wxUSE_HYPERLINKCTRL=yes
@@ -7558,7 +7570,13 @@ if test "$wxUSE_CONTROLS" = "yes"; then
   DEFAULT_wxUSE_CHECKLISTBOX=yes
   DEFAULT_wxUSE_CHOICE=yes
   DEFAULT_wxUSE_CHOICEBOOK=yes
+  DEFAULT_wxUSE_COLOURPICKERCTRL=yes
+  DEFAULT_wxUSE_COMBOBOX=yes
   DEFAULT_wxUSE_DATEPICKCTRL=yes
+  DEFAULT_wxUSE_DISPLAY=yes
+  DEFAULT_wxUSE_DIRPICKERCTRL=yes
+  DEFAULT_wxUSE_FILEPICKERCTRL=yes
+  DEFAULT_wxUSE_FONTPICKERCTRL=yes
   DEFAULT_wxUSE_GAUGE=yes
   DEFAULT_wxUSE_GRID=yes
   DEFAULT_wxUSE_HYPERLINKCTRL=yes
@@ -7602,7 +7620,13 @@ elif test "$wxUSE_CONTROLS" = "no"; then
   DEFAULT_wxUSE_CHECKLISTBOX=no
   DEFAULT_wxUSE_CHOICE=no
   DEFAULT_wxUSE_CHOICEBOOK=no
+  DEFAULT_wxUSE_COLOURPICKERCTRL=no
+  DEFAULT_wxUSE_COMBOBOX=no
   DEFAULT_wxUSE_DATEPICKCTRL=no
+  DEFAULT_wxUSE_DISPLAY=no
+  DEFAULT_wxUSE_DIRPICKERCTRL=no
+  DEFAULT_wxUSE_FILEPICKERCTRL=no
+  DEFAULT_wxUSE_FONTPICKERCTRL=no
   DEFAULT_wxUSE_GAUGE=no
   DEFAULT_wxUSE_GRID=no
   DEFAULT_wxUSE_HYPERLINKCTRL=no
@@ -8008,6 +8032,47 @@ echo "${ECHO_T}no" >&6
 
 
 	  enablestring=
+          echo "$as_me:$LINENO: checking for --${enablestring:-enable}-colourpicker" >&5
+echo $ECHO_N "checking for --${enablestring:-enable}-colourpicker... $ECHO_C" >&6
+          no_cache=0
+          # Check whether --enable-colourpicker or --disable-colourpicker was given.
+if test "${enable_colourpicker+set}" = set; then
+  enableval="$enable_colourpicker"
+
+                          if test "$enableval" = yes; then
+                            ac_cv_use_colourpicker='wxUSE_COLOURPICKERCTRL=yes'
+                          else
+                            ac_cv_use_colourpicker='wxUSE_COLOURPICKERCTRL=no'
+                          fi
+
+else
+
+                          LINE=`grep "wxUSE_COLOURPICKERCTRL" ${wx_arg_cache_file}`
+                          if test "x$LINE" != x ; then
+                            eval "DEFAULT_$LINE"
+                          else
+                            no_cache=1
+                          fi
+
+                          ac_cv_use_colourpicker='wxUSE_COLOURPICKERCTRL='$DEFAULT_wxUSE_COLOURPICKERCTRL
+
+fi;
+
+          eval "$ac_cv_use_colourpicker"
+          if test "$no_cache" != 1; then
+            echo $ac_cv_use_colourpicker >> ${wx_arg_cache_file}.tmp
+          fi
+
+          if test "$wxUSE_COLOURPICKERCTRL" = yes; then
+            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+          else
+            echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+          fi
+
+
+	  enablestring=
           echo "$as_me:$LINENO: checking for --${enablestring:-enable}-combobox" >&5
 echo $ECHO_N "checking for --${enablestring:-enable}-combobox... $ECHO_C" >&6
           no_cache=0
@@ -8131,6 +8196,47 @@ echo "${ECHO_T}no" >&6
 
 
 	  enablestring=
+          echo "$as_me:$LINENO: checking for --${enablestring:-enable}-dirpicker" >&5
+echo $ECHO_N "checking for --${enablestring:-enable}-dirpicker... $ECHO_C" >&6
+          no_cache=0
+          # Check whether --enable-dirpicker or --disable-dirpicker was given.
+if test "${enable_dirpicker+set}" = set; then
+  enableval="$enable_dirpicker"
+
+                          if test "$enableval" = yes; then
+                            ac_cv_use_dirpicker='wxUSE_DIRPICKERCTRL=yes'
+                          else
+                            ac_cv_use_dirpicker='wxUSE_DIRPICKERCTRL=no'
+                          fi
+
+else
+
+                          LINE=`grep "wxUSE_DIRPICKERCTRL" ${wx_arg_cache_file}`
+                          if test "x$LINE" != x ; then
+                            eval "DEFAULT_$LINE"
+                          else
+                            no_cache=1
+                          fi
+
+                          ac_cv_use_dirpicker='wxUSE_DIRPICKERCTRL='$DEFAULT_wxUSE_DIRPICKERCTRL
+
+fi;
+
+          eval "$ac_cv_use_dirpicker"
+          if test "$no_cache" != 1; then
+            echo $ac_cv_use_dirpicker >> ${wx_arg_cache_file}.tmp
+          fi
+
+          if test "$wxUSE_DIRPICKERCTRL" = yes; then
+            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+          else
+            echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+          fi
+
+
+	  enablestring=
           echo "$as_me:$LINENO: checking for --${enablestring:-enable}-display" >&5
 echo $ECHO_N "checking for --${enablestring:-enable}-display... $ECHO_C" >&6
           no_cache=0
@@ -8163,6 +8269,88 @@ fi;
           fi
 
           if test "$wxUSE_DISPLAY" = yes; then
+            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+          else
+            echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+          fi
+
+
+	  enablestring=
+          echo "$as_me:$LINENO: checking for --${enablestring:-enable}-filepicker" >&5
+echo $ECHO_N "checking for --${enablestring:-enable}-filepicker... $ECHO_C" >&6
+          no_cache=0
+          # Check whether --enable-filepicker or --disable-filepicker was given.
+if test "${enable_filepicker+set}" = set; then
+  enableval="$enable_filepicker"
+
+                          if test "$enableval" = yes; then
+                            ac_cv_use_filepicker='wxUSE_FILEPICKERCTRL=yes'
+                          else
+                            ac_cv_use_filepicker='wxUSE_FILEPICKERCTRL=no'
+                          fi
+
+else
+
+                          LINE=`grep "wxUSE_FILEPICKERCTRL" ${wx_arg_cache_file}`
+                          if test "x$LINE" != x ; then
+                            eval "DEFAULT_$LINE"
+                          else
+                            no_cache=1
+                          fi
+
+                          ac_cv_use_filepicker='wxUSE_FILEPICKERCTRL='$DEFAULT_wxUSE_FILEPICKERCTRL
+
+fi;
+
+          eval "$ac_cv_use_filepicker"
+          if test "$no_cache" != 1; then
+            echo $ac_cv_use_filepicker >> ${wx_arg_cache_file}.tmp
+          fi
+
+          if test "$wxUSE_FILEPICKERCTRL" = yes; then
+            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+          else
+            echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+          fi
+
+
+	  enablestring=
+          echo "$as_me:$LINENO: checking for --${enablestring:-enable}-fontpicker" >&5
+echo $ECHO_N "checking for --${enablestring:-enable}-fontpicker... $ECHO_C" >&6
+          no_cache=0
+          # Check whether --enable-fontpicker or --disable-fontpicker was given.
+if test "${enable_fontpicker+set}" = set; then
+  enableval="$enable_fontpicker"
+
+                          if test "$enableval" = yes; then
+                            ac_cv_use_fontpicker='wxUSE_FONTPICKERCTRL=yes'
+                          else
+                            ac_cv_use_fontpicker='wxUSE_FONTPICKERCTRL=no'
+                          fi
+
+else
+
+                          LINE=`grep "wxUSE_FONTPICKERCTRL" ${wx_arg_cache_file}`
+                          if test "x$LINE" != x ; then
+                            eval "DEFAULT_$LINE"
+                          else
+                            no_cache=1
+                          fi
+
+                          ac_cv_use_fontpicker='wxUSE_FONTPICKERCTRL='$DEFAULT_wxUSE_FONTPICKERCTRL
+
+fi;
+
+          eval "$ac_cv_use_fontpicker"
+          if test "$no_cache" != 1; then
+            echo $ac_cv_use_fontpicker >> ${wx_arg_cache_file}.tmp
+          fi
+
+          if test "$wxUSE_FONTPICKERCTRL" = yes; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
           else
@@ -27703,6 +27891,76 @@ echo "${ECHO_T}yes" >&6
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 
+                        echo "$as_me:$LINENO: checking if GTK+ is version >= 2.6" >&5
+echo $ECHO_N "checking if GTK+ is version >= 2.6... $ECHO_C" >&6
+            cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+                            #include <gtk/gtk.h>
+
+int
+main ()
+{
+
+                            #if !GTK_CHECK_VERSION(2,6,0)
+                            Not GTK+ 2.6
+                            #endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+                            cat >>confdefs.h <<\_ACEOF
+#define __WXGTK26__ 1
+_ACEOF
+
+                            cat >>confdefs.h <<\_ACEOF
+#define __WXGTK24__ 1
+_ACEOF
+
+                            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+                            ac_wxgtk26=1
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+                            echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+                            ac_wxgtk26=0
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+
+            if test "$ac_wxgtk26" = 0; then
                         echo "$as_me:$LINENO: checking if GTK+ is version >= 2.4" >&5
 echo $ECHO_N "checking if GTK+ is version >= 2.4... $ECHO_C" >&6
             cat >conftest.$ac_ext <<_ACEOF
@@ -27765,6 +28023,7 @@ echo "${ECHO_T}no" >&6
 
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+            fi
 
             CFLAGS="$save_CFLAGS"
             LIBS="$save_LIBS"
@@ -43801,9 +44060,41 @@ _ACEOF
   SAMPLES_SUBDIRS="$SAMPLES_SUBDIRS checklst"
 fi
 
+if test "$wxUSE_COLOURPICKERCTRL" = "yes"; then
+  cat >>confdefs.h <<\_ACEOF
+#define wxUSE_COLOURPICKERCTRL 1
+_ACEOF
+
+  USES_CONTROLS=1
+fi
+
 if test "$wxUSE_DATEPICKCTRL" = "yes"; then
   cat >>confdefs.h <<\_ACEOF
 #define wxUSE_DATEPICKCTRL 1
+_ACEOF
+
+  USES_CONTROLS=1
+fi
+
+if test "$wxUSE_DIRPICKERCTRL" = "yes"; then
+  cat >>confdefs.h <<\_ACEOF
+#define wxUSE_DIRPICKERCTRL 1
+_ACEOF
+
+  USES_CONTROLS=1
+fi
+
+if test "$wxUSE_FILEPICKERCTRL" = "yes"; then
+  cat >>confdefs.h <<\_ACEOF
+#define wxUSE_FILEPICKERCTRL 1
+_ACEOF
+
+  USES_CONTROLS=1
+fi
+
+if test "$wxUSE_FONTPICKERCTRL" = "yes"; then
+  cat >>confdefs.h <<\_ACEOF
+#define wxUSE_FONTPICKERCTRL 1
 _ACEOF
 
   USES_CONTROLS=1
