Only automatically switch off --enable-std_string or --enable-std_iostreams if they are not on the command line, fail with an error otherwise.
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/trunk@34008 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21315,8 +21315,12 @@ sed 's/^/| /' conftest.$ac_ext >&5
 echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
                          if test "$wxUSE_STL" = "yes"; then
-                             { { echo "$as_me:$LINENO: error: Can't compile with --enable-stl without $std_string or std::basic_string<$char_type>" >&5
-echo "$as_me: error: Can't compile with --enable-stl without $std_string or std::basic_string<$char_type>" >&2;}
+                             { { echo "$as_me:$LINENO: error: Can't use --enable-stl without $std_string or std::basic_string<$char_type>" >&5
+echo "$as_me: error: Can't use --enable-stl without $std_string or std::basic_string<$char_type>" >&2;}
+   { (exit 1); exit 1; }; }
+                         elif grep wxUSE_STD_STRING $wx_arg_cache_file >/dev/null; then
+                             { { echo "$as_me:$LINENO: error: Can't use --enable-std_string without $std_string or std::basic_string<$char_type>" >&5
+echo "$as_me: error: Can't use --enable-std_string without $std_string or std::basic_string<$char_type>" >&2;}
    { (exit 1); exit 1; }; }
                          else
                              { echo "$as_me:$LINENO: WARNING: No $std_string or std::basic_string<$char_type>, switching to --disable-std_string" >&5
@@ -21482,8 +21486,14 @@ fi
 
 
     if test "$wxUSE_STD_IOSTREAM" != "yes"; then
-        { echo "$as_me:$LINENO: WARNING: No std::iostreams, switching to --disable-std_iostreams" >&5
+        if grep wxUSE_STD_IOSTREAM $wx_arg_cache_file >/dev/null; then
+            { { echo "$as_me:$LINENO: error: Can't use --enable-std_iostreams without std::istream and std::ostream" >&5
+echo "$as_me: error: Can't use --enable-std_iostreams without std::istream and std::ostream" >&2;}
+   { (exit 1); exit 1; }; }
+        else
+            { echo "$as_me:$LINENO: WARNING: No std::iostreams, switching to --disable-std_iostreams" >&5
 echo "$as_me: WARNING: No std::iostreams, switching to --disable-std_iostreams" >&2;}
+        fi
     fi
 
     ac_ext=c
