Completed inotify file system watcher implementation. Update of build files to search for sys/inotify.h File system watcher test cleaned and improved.
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/branches/SOC2009_FSWATCHER@61222 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -42223,6 +42223,86 @@ _ACEOF
     fi
 fi
 
+if test "$wxUSE_FSWATCHER" = "yes"; then
+	cat >>confdefs.h <<\_ACEOF
+#define wxUSE_FSWATCHER 1
+_ACEOF
+
+
+	if test "$wxUSE_UNIX" = "yes" ; then
+
+for ac_header in sys/inotify.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  eval "$as_ac_Header=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	eval "$as_ac_Header=no"
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+
+done
+
+		if test "$ac_cv_header_sys_inotify_h" = "yes"; then
+	        cat >>confdefs.h <<\_ACEOF
+#define HAVE_INOTIFY_H 1
+_ACEOF
+
+	    else
+	        { echo "$as_me:$LINENO: WARNING: sys/inotify.h not available, \
+	        				wxInotifyFileSystemWatcher disabled" >&5
+echo "$as_me: WARNING: sys/inotify.h not available, \
+	        				wxInotifyFileSystemWatcher disabled" >&2;}
+	    fi
+    fi
+fi
+
+
 
 if test "$wxUSE_STL" = "yes"; then
   cat >>confdefs.h <<\_ACEOF
@@ -42252,12 +42332,6 @@ _ACEOF
 
 fi
 
-if test "$wxUSE_FSWATCHER" = "yes"; then
-  cat >>confdefs.h <<\_ACEOF
-#define wxUSE_FSWATCHER 1
-_ACEOF
-
-fi
 
 if test "$USE_UNIX" = 1 ; then
         if test "$wxUSE_MGL" != 1; then
