Rebake after MSLU and other changes
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/trunk@35063 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13375,7 +13375,7 @@ fi
 
 
 
-if test "x$XLCXX" = "xyes"; then
+if test "x$XLCXX" = "xyes" -a "x$USE_AIX" = "x1"; then
     CXXFLAGS="$CXXFLAGS -qunique"
 fi
 
@@ -28626,6 +28626,74 @@ echo "${ECHO_T}not found" >&6
 
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+
+        echo "$as_me:$LINENO: checking whether Motif is Lesstif" >&5
+echo $ECHO_N "checking whether Motif is Lesstif... $ECHO_C" >&6
+        cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+                        #include <Xm/Xm.h>
+
+int
+main ()
+{
+
+                        #if !defined(LesstifVersion) || LesstifVersion <= 0
+                        #error "Not Lesstif"
+                        #endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+                        cat >>confdefs.h <<\_ACEOF
+#define __WXLESSTIF__ 1
+_ACEOF
+
+                        echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+                        cat >>confdefs.h <<\_ACEOF
+#define __WXLESSTIF__ 0
+_ACEOF
+
+                        echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
         CFLAGS=$save_CFLAGS
 
         GUI_TK_LIBRARY="$GUI_TK_LIBRARY -lXm${libp_link} -lXmu -lXext -lXt${libsm_ice_link} -lX11"
@@ -39786,10 +39854,16 @@ _ACEOF
 fi
 
 if test "$wxUSE_DATAOBJ" = "yes"; then
-    cat >>confdefs.h <<\_ACEOF
+    if test "$wxUSE_MGL" = 1; then
+        { echo "$as_me:$LINENO: WARNING: wxDataObject not yet supported under MGL... disabled" >&5
+echo "$as_me: WARNING: wxDataObject not yet supported under MGL... disabled" >&2;}
+        wxUSE_DATAOBJ=no
+    else
+        cat >>confdefs.h <<\_ACEOF
 #define wxUSE_DATAOBJ 1
 _ACEOF
 
+    fi
 else
     { echo "$as_me:$LINENO: WARNING: Clipboard and drag-and-drop require wxDataObject -- disabled" >&5
 echo "$as_me: WARNING: Clipboard and drag-and-drop require wxDataObject -- disabled" >&2;}
@@ -42500,6 +42574,7 @@ while test ${D}# -gt 0; do
        -s|-Wl,*)
         # collect these load args
         ldargs="${D}{ldargs} ${D}1"
+        ;;
 
        -l*|-L*|-flat_namespace|-headerpad_max_install_names)
         # collect these options
