made GTK+2 the default
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/trunk@28277 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -872,7 +872,7 @@ Optional Features:
   --enable-plugins        build parts of wxWidgets as loadable components
   --enable-universal      use wxWidgets GUI controls instead of native ones
   --enable-nanox          use NanoX
-  --enable-gtk2           use GTK+ 2.0 if available
+  --disable-gtk2          use GTK+ 1.2 instead of 2.0
   --enable-gpe            use GNOME PDA Environment features if possible
   --enable-shared         create shared library code
   --enable-optimise       create optimised code
@@ -2376,6 +2376,8 @@ else
   DEFAULT_wxUSE_MONOLITHIC=no
   DEFAULT_wxUSE_PLUGINS=no
   DEFAULT_wxUSE_OFFICIAL_BUILD=no
+
+    DEFAULT_wxUSE_GTK2=yes
 fi
 
 
@@ -18715,6 +18717,12 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
 
+  if test "$cross_compiling" = "yes"; then
+    cat >>confdefs.h <<\_ACEOF
+#define wxUSE_IOSTREAMH 1
+_ACEOF
+
+  else
 
 
     ac_ext=cc
@@ -18890,6 +18898,7 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
+  fi
 
 
 
@@ -38830,18 +38839,18 @@ CleanUp() {
 
     # Kill result in case of failure as there is just to many stupid make/nmake
     # things out there which doesn't do this.
-    if  ${D}# -eq 0 ; then
+    if [] ${D}# -eq 0 []; then
         rm -f ${D}arcFile ${D}arcFile2 ${D}defFile ${D}dllFile
     fi
 }
 
 # Print usage and exit script with rc=1.
 PrintHelp() {
- echo 'Usage: dllar -o[utput] output_file -i[mport] importlib_name'
- echo '       -d[escription] "dll descrption" -cc "CC" -f[lags] "CFLAGS"'
- echo '       -ord[inals] -exclude "symbol(s)"'
- echo '       -libf[lags] "{INIT|TERM}{GLOBAL|INSTANCE}" -nocrt[dll] -nolxl[ite]'
- echo '       *.o *.a'
+ echo 'Usage: dllar []-o[[]utput[]] output_file[] []-i[[]mport[]] importlib_name[]'
+ echo '       []-d[[]escription[]] "dll descrption"[] []-cc "CC"[] []-f[[]lags[]] "CFLAGS"[]'
+ echo '       []-ord[[]inals[]][] -ex[]clude[] "symbol(s)"'
+ echo '       []-libf[[]lags[]] "{INIT|TERM}{GLOBAL|INSTANCE}"[] []-nocrt[[]dll[]][] []-nolxl[[]ite[]][]'
+ echo '       []*.o[] []*.a[]'
  echo '*> "output_file" should have no extension.'
  echo '   If it has the .o, .a or .dll extension, it is automatically removed.'
  echo '   The import library name is derived from this and is set to "name".a,'
@@ -38854,16 +38863,16 @@ PrintHelp() {
  echo '*> "cc" is used to use another GCC executable.   (default: gcc.exe)'
  echo '*> "flags" should be any set of valid GCC flags. (default: -s -Zcrtdll)'
  echo '   These flags will be put at the start of GCC command line.'
- echo '*> -ordinals tells dllar to export entries by ordinals. Be careful.'
- echo '*> -exclude defines symbols which will not be exported. You can define'
+ echo '*> -ord[]inals[] tells dllar to export entries by ordinals. Be careful.'
+ echo '*> -ex[]clude[] defines symbols which will not be exported. You can define'
  echo '   multiple symbols, for example -ex "myfunc yourfunc _GLOBAL*".'
  echo '   If the last character of a symbol is "*", all symbols beginning'
  echo '   with the prefix before "*" will be exclude, (see _GLOBAL* above).'
- echo '*> -libflags can be used to add INITGLOBAL/INITINSTANCE and/or'
+ echo '*> -libf[]lags[] can be used to add INITGLOBAL/INITINSTANCE and/or'
  echo '   TERMGLOBAL/TERMINSTANCE flags to the dynamically-linked library.'
- echo '*> -nocrtdll switch will disable linking the library against emx''s'
+ echo '*> -nocrt[]dll[] switch will disable linking the library against emx''s'
  echo '   C runtime DLLs.'
- echo '*> -nolxlite switch will disable running lxlite on the resulting DLL.'
+ echo '*> -nolxl[]ite[] switch will disable running lxlite on the resulting DLL.'
  echo '*> All other switches (for example -L./ or -lmylib) will be passed'
  echo '   unchanged to GCC at the end of command line.'
  echo '*> If you create a DLL from a library and you do not specify -o,'
@@ -38887,7 +38896,7 @@ doCommand() {
     eval ${D}*
     rcCmd=${D}?
 
-    if  ${D}rcCmd -ne 0 ; then
+    if [] ${D}rcCmd -ne 0 []; then
         echo "command failed, exit code="${D}rcCmd
         CleanUp
         exit ${D}rcCmd
@@ -38918,7 +38927,7 @@ case ${D}curDirS in
 esac
 # Parse commandline
 libsToLink=0
-while  ${D}1 ; do
+while [] ${D}1 []; do
     case ${D}1 in
     -ord*)
         EXPORT_BY_ORDINALS=1;
@@ -38972,16 +38981,16 @@ while  ${D}1 ; do
         ;;
     *)
         found=0;
-        if  ${D}libsToLink -ne 0 ; then
+        if [] ${D}libsToLink -ne 0 []; then
             EXTRA_CFLAGS=${D}{EXTRA_CFLAGS}" "${D}1
         else
             for file in ${D}1 ; do
-                if  -f ${D}file ; then
+                if [] -f ${D}file []; then
                     inputFiles="${D}{inputFiles} ${D}file"
                     found=1
                 fi
             done
-            if  ${D}found -eq 0 ; then
+            if [] ${D}found -eq 0 []; then
                 echo "ERROR: No file(s) found: "${D}1
                 exit 8
             fi
@@ -38992,7 +39001,7 @@ while  ${D}1 ; do
 done # iterate cmdline words
 
 #
-if  -z "${D}inputFiles" ; then
+if [] -z "${D}inputFiles" []; then
     echo "dllar: no input files"
     PrintHelp
 fi
@@ -39017,7 +39026,7 @@ for file in ${D}inputFiles ; do
         esac
         dirname=\`basnam ${D}file ${D}suffix\`"_%"
         mkdir ${D}dirname
-        if  ${D}? -ne 0 ; then
+        if [] ${D}? -ne 0 []; then
             echo "Failed to create subdirectory ./${D}dirname"
             CleanUp
             exit 8;
@@ -39028,15 +39037,15 @@ for file in ${D}inputFiles ; do
         cd ${D}curDir
         found=0;
         for subfile in ${D}dirname/*.o* ; do
-            if  -f ${D}subfile ; then
+            if [] -f ${D}subfile []; then
                 found=1
-                if  -s ${D}subfile ; then
+                if [] -s ${D}subfile []; then
 	            # FIXME: This should be: is file size > 32 byte, _not_ > 0!
                     newInputFiles="${D}newInputFiles ${D}subfile"
                 fi
             fi
         done
-        if  ${D}found -eq 0 ; then
+        if [] ${D}found -eq 0 []; then
             echo "WARNING: there are no files in archive \'${D}file\'"
         fi
         ;;
@@ -39049,7 +39058,7 @@ inputFiles="${D}newInputFiles"
 
 # Output filename(s).
 do_backup=0;
-if  -z ${D}outFile ; then
+if [] -z ${D}outFile []; then
     do_backup=1;
     set outFile ${D}inputFiles; outFile=${D}2
 fi
@@ -39094,7 +39103,7 @@ case ${D}outimpFile in
 *)
     ;;
 esac
-if  -z ${D}outimpFile ; then
+if [] -z ${D}outimpFile []; then
     outimpFile=${D}outFile
 fi
 defFile="${D}{outFile}.def"
@@ -39104,11 +39113,11 @@ dllFile="${D}outFile"
 # Add suffix to dllFile later, first we need a version to use as
 # name in .def file.
 
-if  ${D}do_backup -ne 0  ; then
-    if  -f ${D}arcFile  ; then
+if [] ${D}do_backup -ne 0 [] ; then
+    if [] -f ${D}arcFile [] ; then
         doCommand "mv ${D}arcFile ${D}{outFile}_s.a"
     fi
-    if  -f ${D}arcFile2  ; then
+    if [] -f ${D}arcFile2 [] ; then
         doCommand "mv ${D}arcFile2 ${D}{outFile}_s.lib"
     fi
 fi
@@ -39130,7 +39139,7 @@ done
 rm -f ${D}defFile
 echo "LIBRARY \`basnam ${D}dllFile\` ${D}library_flags" >> ${D}defFile
 dllFile="${D}dllFile.dll"
-if  -n ${D}description ; then
+if [] -n ${D}description []; then
     echo "DESCRIPTION  \"${D}{description}\"" >> ${D}defFile
 fi
 echo "EXPORTS" >> ${D}defFile
@@ -39145,12 +39154,12 @@ for word in ${D}exclude_symbols; do
 done
 
 
-if  ${D}EXPORT_BY_ORDINALS -ne 0 ; then
+if [] ${D}EXPORT_BY_ORDINALS -ne 0 []; then
     sed "=" < ${D}tmpdefFile | \
     sed '
       N
       : loop
-      s/^\(0-9\+\)\(^;*\)\(;.*\)\?/\2 @\1 NONAME/
+      s/^\([]0-9[]\+\)\([]^;[]*\)\(;.*\)\?/\2 @\1 NONAME/
       t loop
     ' > ${D}{tmpdefFile}%
     grep -v "^ *${D}" < ${D}{tmpdefFile}% > ${D}tmpdefFile
@@ -39175,9 +39184,9 @@ doCommand "${D}CC ${D}CFLAGS -Zdll -o ${D}dllFile ${D}defFile ${D}gccCmdl ${D}EX
 touch "${D}{outFile}.dll"
 
 doCommand "emximp -o ${D}arcFile ${D}defFile"
-if  ${D}flag_USE_LXLITE -ne 0 ; then
+if [] ${D}flag_USE_LXLITE -ne 0 []; then
     add_flags="";
-    if  ${D}EXPORT_BY_ORDINALS -ne 0 ; then
+    if [] ${D}EXPORT_BY_ORDINALS -ne 0 []; then
         add_flags="-ynd"
     fi
     doCommand "lxlite -cs -t: -mrn -mln ${D}add_flags ${D}dllFile"
@@ -39204,6 +39213,10 @@ EOF
 echo "$as_me: error: unknown system type $BAKEFILE_HOST." >&2;}
    { (exit 1); exit 1; }; }
     esac
+
+    if test "x$PIC_FLAG" != "x" ; then
+        PIC_FLAG="$PIC_FLAG -DPIC"
+    fi
 
     if test "x$SHARED_LD_MODULE_CC" = "x" ; then
         SHARED_LD_MODULE_CC="$SHARED_LD_CC"
@@ -39468,9 +39481,10 @@ fi
 
 
 
+    BAKEFILE_BAKEFILE_M4_VERSION="0.1.4"
+
 
 BAKEFILE_AUTOCONF_INC_M4_VERSION="0.1.4"
-
 
 
 
@@ -40827,6 +40841,12 @@ EOF
 
 
 
+    if test "$BAKEFILE_BAKEFILE_M4_VERSION" != "$BAKEFILE_AUTOCONF_INC_M4_VERSION" ; then
+        { { echo "$as_me:$LINENO: error: Versions of Bakefile used to generate makefiles ($BAKEFILE_AUTOCONF_INC_M4_VERSION) and configure ($BAKEFILE_BAKEFILE_M4_VERSION) do not match." >&5
+echo "$as_me: error: Versions of Bakefile used to generate makefiles ($BAKEFILE_AUTOCONF_INC_M4_VERSION) and configure ($BAKEFILE_BAKEFILE_M4_VERSION) do not match." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
 
 
 GCC_PRAGMA_FLAGS=""
@@ -41130,8 +41150,6 @@ echo $ECHO_N "checking for Cppunit - version >= $cppunit_version_min... $ECHO_C"
   no_cppunit=""
   if test "$CPPUNIT_CONFIG" = "no" ; then
     no_cppunit=yes
-    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
   else
     CPPUNIT_CFLAGS=`$CPPUNIT_CONFIG --cflags`
     CPPUNIT_LIBS=`$CPPUNIT_CONFIG --libs`
