Regenerate configure after gtk.m4 update
This should have been part of 8e35398037c683e44f88ea084c9abbe64e69fafc.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21674,7 +21674,7 @@ if ac_fn_c_try_link "$LINENO"; then :
           echo "*** you may also be able to get things to work by modifying LD_LIBRARY_PATH"
 else
    echo "*** The test program failed to compile or link. See the file config.log for the"
-          echo "*** exact error that occured. This usually means GTK+ is incorrectly installed."
+          echo "*** exact error that occurred. This usually means GTK+ is incorrectly installed."
 fi
 rm -f core conftest.err conftest.$ac_objext \
     conftest$ac_exeext conftest.$ac_ext
@@ -21821,13 +21821,13 @@ main ()
      exit(1);
    }
 
-  if ((GTK_MAJOR_VERSION != $gtk_config_major_version) ||
-      (GTK_MINOR_VERSION != $gtk_config_minor_version) ||
-      (GTK_MICRO_VERSION != $gtk_config_micro_version))
+  if ((gtk_get_major_version() != $gtk_config_major_version) ||
+      (gtk_get_minor_version() != $gtk_config_minor_version) ||
+      (gtk_get_micro_version() != $gtk_config_micro_version))
     {
       printf("\n*** 'pkg-config --modversion gtk+-4.0' returned %d.%d.%d, but GTK+ (%d.%d.%d)\n",
              $gtk_config_major_version, $gtk_config_minor_version, $gtk_config_micro_version,
-             GTK_MAJOR_VERSION, GTK_MINOR_VERSION, GTK_MICRO_VERSION);
+             gtk_get_major_version(), gtk_get_minor_version(), gtk_get_micro_version());
       printf ("*** was found! If pkg-config was correct, then it is best\n");
       printf ("*** to remove the old version of GTK+. You may also be able to fix the error\n");
       printf("*** by modifying your LD_LIBRARY_PATH enviroment variable, or by editing\n");
@@ -21836,18 +21836,27 @@ main ()
       printf("*** If pkg-config was wrong, set the environment variable PKG_CONFIG_PATH\n");
       printf("*** to point to the correct configuration files\n");
     }
+  else if ((gtk_get_major_version() != GTK_MAJOR_VERSION) ||
+	   (gtk_get_minor_version() != GTK_MINOR_VERSION) ||
+           (gtk_get_micro_version() != GTK_MICRO_VERSION))
+    {
+      printf("*** GTK+ header files (version %d.%d.%d) do not match\n",
+	     GTK_MAJOR_VERSION, GTK_MINOR_VERSION, GTK_MICRO_VERSION);
+      printf("*** library (version %d.%d.%d)\n",
+	     gtk_get_major_version(), gtk_get_minor_version(), gtk_get_micro_version());
+    }
   else
     {
-      if ((GTK_MAJOR_VERSION > major) ||
-        ((GTK_MAJOR_VERSION == major) && (GTK_MINOR_VERSION > minor)) ||
-        ((GTK_MAJOR_VERSION == major) && (GTK_MINOR_VERSION == minor) && (GTK_MICRO_VERSION >= micro)))
+      if ((gtk_get_major_version() > major) ||
+        ((gtk_get_major_version() == major) && (gtk_get_minor_version() > minor)) ||
+        ((gtk_get_major_version() == major) && (gtk_get_minor_version() == minor) && (gtk_get_micro_version() >= micro)))
       {
         return 0;
        }
      else
       {
         printf("\n*** An old version of GTK+ (%u.%u.%u) was found.\n",
-               GTK_MAJOR_VERSION, GTK_MINOR_VERSION, GTK_MICRO_VERSION);
+               gtk_get_major_version(), gtk_get_minor_version(), gtk_get_micro_version());
         printf("*** You need a version of GTK+ newer than %u.%u.%u. The latest version of\n",
 	       major, minor, micro);
         printf("*** GTK+ is always available from ftp://ftp.gtk.org.\n");
@@ -21906,7 +21915,7 @@ $as_echo "no" >&6; }
 int
 main ()
 {
- return ((gtk_major_version) || (gtk_minor_version) || (gtk_micro_version));
+ return ((gtk_get_major_version()) || (gtk_get_minor_version()) || (gtk_get_micro_version()));
   ;
   return 0;
 }
@@ -21923,7 +21932,7 @@ if ac_fn_c_try_link "$LINENO"; then :
           echo "*** you may also be able to get things to work by modifying LD_LIBRARY_PATH"
 else
    echo "*** The test program failed to compile or link. See the file config.log for the"
-          echo "*** exact error that occured. This usually means GTK+ is incorrectly installed."
+          echo "*** exact error that occurred. This usually means GTK+ is incorrectly installed."
 fi
 rm -f core conftest.err conftest.$ac_objext \
     conftest$ac_exeext conftest.$ac_ext
