removed wxUSE_TOOLBAR_SIMPLE leftovers from the main sources, it's not used anywhere anymore
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/trunk@40766 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1075,7 +1075,6 @@ Optional Features:
   --enable-togglebtn      use wxToggleButton class
   --enable-toolbar        use wxToolBar class
   --enable-tbarnative     use native wxToolBar class
-  --enable-tbarsmpl       use wxToolBarSimple class
   --enable-treebook       use wxTreebook class
   --enable-toolbook       use wxToolbook class
   --enable-treectrl       use wxTreeCtrl class
@@ -2330,7 +2329,6 @@ if test $DEBUG_CONFIGURE = 1; then
   DEFAULT_wxUSE_TOGGLEBTN=no
   DEFAULT_wxUSE_TOOLBAR=no
   DEFAULT_wxUSE_TOOLBAR_NATIVE=no
-  DEFAULT_wxUSE_TOOLBAR_SIMPLE=no
   DEFAULT_wxUSE_TREEBOOK=no
   DEFAULT_wxUSE_TOOLBOOK=no
   DEFAULT_wxUSE_TREECTRL=no
@@ -2543,7 +2541,6 @@ else
   DEFAULT_wxUSE_TOGGLEBTN=yes
   DEFAULT_wxUSE_TOOLBAR=yes
   DEFAULT_wxUSE_TOOLBAR_NATIVE=yes
-  DEFAULT_wxUSE_TOOLBAR_SIMPLE=yes
   DEFAULT_wxUSE_TREEBOOK=yes
   DEFAULT_wxUSE_TOOLBOOK=yes
   DEFAULT_wxUSE_TREECTRL=yes
@@ -7728,7 +7725,6 @@ if test "$wxUSE_CONTROLS" = "yes"; then
   DEFAULT_wxUSE_TOGGLEBTN=yes
   DEFAULT_wxUSE_TOOLBAR=yes
   DEFAULT_wxUSE_TOOLBAR_NATIVE=yes
-  DEFAULT_wxUSE_TOOLBAR_SIMPLE=yes
   DEFAULT_wxUSE_TOOLTIPS=yes
   DEFAULT_wxUSE_TREEBOOK=yes
   DEFAULT_wxUSE_TOOLBOOK=yes
@@ -7778,7 +7774,6 @@ elif test "$wxUSE_CONTROLS" = "no"; then
   DEFAULT_wxUSE_TOGGLEBTN=no
   DEFAULT_wxUSE_TOOLBAR=no
   DEFAULT_wxUSE_TOOLBAR_NATIVE=no
-  DEFAULT_wxUSE_TOOLBAR_SIMPLE=no
   DEFAULT_wxUSE_TOOLTIPS=no
   DEFAULT_wxUSE_TREEBOOK=no
   DEFAULT_wxUSE_TOOLBOOK=no
@@ -9625,47 +9620,6 @@ fi;
           fi
 
           if test "$wxUSE_TOOLBAR_NATIVE" = yes; then
-            echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-          else
-            echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-          fi
-
-
-	  enablestring=
-          echo "$as_me:$LINENO: checking for --${enablestring:-enable}-tbarsmpl" >&5
-echo $ECHO_N "checking for --${enablestring:-enable}-tbarsmpl... $ECHO_C" >&6
-          no_cache=0
-          # Check whether --enable-tbarsmpl or --disable-tbarsmpl was given.
-if test "${enable_tbarsmpl+set}" = set; then
-  enableval="$enable_tbarsmpl"
-
-                          if test "$enableval" = yes; then
-                            ac_cv_use_tbarsmpl='wxUSE_TOOLBAR_SIMPLE=yes'
-                          else
-                            ac_cv_use_tbarsmpl='wxUSE_TOOLBAR_SIMPLE=no'
-                          fi
-
-else
-
-                          LINE=`grep "wxUSE_TOOLBAR_SIMPLE" ${wx_arg_cache_file}`
-                          if test "x$LINE" != x ; then
-                            eval "DEFAULT_$LINE"
-                          else
-                            no_cache=1
-                          fi
-
-                          ac_cv_use_tbarsmpl='wxUSE_TOOLBAR_SIMPLE='$DEFAULT_wxUSE_TOOLBAR_SIMPLE
-
-fi;
-
-          eval "$ac_cv_use_tbarsmpl"
-          if test "$no_cache" != 1; then
-            echo $ac_cv_use_tbarsmpl >> ${wx_arg_cache_file}.tmp
-          fi
-
-          if test "$wxUSE_TOOLBAR_SIMPLE" = yes; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
           else
@@ -12181,7 +12135,7 @@ echo "${ECHO_T}$ac_cv_c_compiler_gnu" >&6
 GCC=`test $ac_compiler_gnu = yes && echo yes`
 ac_test_CFLAGS=${CFLAGS+set}
 ac_save_CFLAGS=$CFLAGS
-CFLAGS="-g"
+CFLAGS="$CFLAGS -g"
 echo "$as_me:$LINENO: checking whether $CC accepts -g" >&5
 echo $ECHO_N "checking whether $CC accepts -g... $ECHO_C" >&6
 if test "${ac_cv_prog_cc_g+set}" = set; then
@@ -12653,7 +12607,7 @@ fi
                 unset ac_cv_prog_cc_g
                 ac_test_CFLAGS=${CFLAGS+set}
 ac_save_CFLAGS=$CFLAGS
-CFLAGS="-g"
+CFLAGS="$CFLAGS -g"
 echo "$as_me:$LINENO: checking whether $CC accepts -g" >&5
 echo $ECHO_N "checking whether $CC accepts -g... $ECHO_C" >&6
 if test "${ac_cv_prog_cc_g+set}" = set; then
@@ -13825,9 +13779,9 @@ if test "$ac_test_CXXFLAGS" = set; then
   CXXFLAGS=$ac_save_CXXFLAGS
 elif test $ac_cv_prog_cxx_g = yes; then
   if test "$GXX" = yes; then
-    CXXFLAGS="-g -O2"
+    CXXFLAGS="$CXXFLAGS -g -O2"
   else
-    CXXFLAGS="-g"
+    CXXFLAGS="$CXXFLAGS -g"
   fi
 else
   if test "$GXX" = yes; then
@@ -14090,7 +14044,7 @@ fi
                 unset ac_cv_prog_cc_g
                 ac_test_CFLAGS=${CFLAGS+set}
 ac_save_CFLAGS=$CFLAGS
-CFLAGS="-g"
+CFLAGS="$CFLAGS -g"
 echo "$as_me:$LINENO: checking whether $CC accepts -g" >&5
 echo $ECHO_N "checking whether $CC accepts -g... $ECHO_C" >&6
 if test "${ac_cv_prog_cc_g+set}" = set; then
@@ -34613,10 +34567,8 @@ if test "${wx_cv_func_snprintf_pos_params+set}" = set; then
 else
 
                 if test "$cross_compiling" = yes; then
-  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
-See \`config.log' for more details." >&5
-echo "$as_me: error: cannot run test program while cross compiling
-See \`config.log' for more details." >&2;}
+  { { echo "$as_me:$LINENO: error: internal error: not reached in cross-compile" >&5
+echo "$as_me: error: internal error: not reached in cross-compile" >&2;}
    { (exit 1); exit 1; }; }
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -44854,15 +44806,6 @@ _ACEOF
     fi
 fi
 
-if test "$wxUSE_TOOLBAR_SIMPLE" = "yes"; then
-    cat >>confdefs.h <<\_ACEOF
-#define wxUSE_TOOLBAR_SIMPLE 1
-_ACEOF
-
-    wxUSE_TOOLBAR="yes"
-    USES_CONTROLS=1
-fi
-
 if test "$wxUSE_TOOLBAR" = "yes"; then
     cat >>confdefs.h <<\_ACEOF
 #define wxUSE_TOOLBAR 1
@@ -44870,16 +44813,12 @@ _ACEOF
 
     USES_CONTROLS=1
 
-        if test "$wxUSE_TOOLBAR_SIMPLE" != "yes"; then
-        wxUSE_TOOLBAR_NATIVE="yes"
-    fi
-
+    wxUSE_TOOLBAR_NATIVE="yes"
     if test "$wxUSE_TOOLBAR_NATIVE" = "yes"; then
         cat >>confdefs.h <<\_ACEOF
 #define wxUSE_TOOLBAR_NATIVE 1
 _ACEOF
 
-        USES_CONTROLS=1
     fi
 
     SAMPLES_SUBDIRS="$SAMPLES_SUBDIRS toolbar"
