Added test case speficically for GCC >= 4.0 and    define NO_GCC_PRAGMA then.
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/trunk@34773 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -44235,9 +44235,65 @@ fi
 
 GCC_PRAGMA_FLAGS=""
 PCH_FLAGS=""
+
 if test $GCC_PCH = 1 ; then
-    GCC_PRAGMA_FLAGS="-DNO_GCC_PRAGMA"
     PCH_FLAGS="-DWX_PRECOMP"
+fi
+
+if test "$GCC" = yes; then
+    echo "$as_me:$LINENO: checking if this GCC version is >= 4.0 and needs -DNO_GCC_PRAGMA" >&5
+echo $ECHO_N "checking if this GCC version is >= 4.0 and needs -DNO_GCC_PRAGMA... $ECHO_C" >&6
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+#if (__GNUC__ < 4)
+         #error "Not GCC 4.0 or greater"
+         #endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  GCC_PRAGMA_FLAGS="-DNO_GCC_PRAGMA"
+         echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 else
     case "${host}" in
         powerpc-*-darwin* )
@@ -44302,7 +44358,7 @@ fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
             fi
             ;;
-	*-pc-os2_emx | *-pc-os2-emx )
+        *-pc-os2_emx | *-pc-os2-emx )
                                                 if test "$wxUSE_STL" = "yes"; then
                echo "$as_me:$LINENO: checking if this gcc version needs -DNO_GCC_PRAGMA" >&5
 echo $ECHO_N "checking if this gcc version needs -DNO_GCC_PRAGMA... $ECHO_C" >&6
