abort immediately if no C++ compiler was detected instead of continuing reporting plenty of tests failures
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/trunk@45928 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -16316,6 +16316,12 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+if test -n "$ac_cv_prog_ac_ct_CXX"; then
+    { { echo "$as_me:$LINENO: error: C++ compiler is needed to build wxWidgets" >&5
+echo "$as_me: error: C++ compiler is needed to build wxWidgets" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 if test -n "$ac_tool_prefix"; then
   # Extract the first word of "${ac_tool_prefix}ranlib", so it can be a program name with args.
 set dummy ${ac_tool_prefix}ranlib; ac_word=$2
