applied modified patch with native GTK wxFileDialog
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/trunk@30622 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23712,6 +23712,7 @@ equivalent variable and GTK+ is version 1.2.3 or above.
             CFLAGS="$CFLAGS $GTK_CFLAGS"
             LIBS="$LIBS $GTK_LIBS"
 
+
 for ac_func in pango_font_family_is_monospace
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
@@ -23812,6 +23813,71 @@ _ACEOF
 
 fi
 done
+
+
+                        echo "$as_me:$LINENO: checking if GTK+ is version >= 2.4" >&5
+echo $ECHO_N "checking if GTK+ is version >= 2.4... $ECHO_C" >&6
+            cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+                            #include <gtk/gtk.h>
+
+int
+main ()
+{
+
+                            #if !GTK_CHECK_VERSION(2,4,0)
+                            #error "Not GTK+ 2.4"
+                            #endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+                            cat >>confdefs.h <<\_ACEOF
+#define __WXGTK24__ 1
+_ACEOF
+
+                            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+                            echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 
             CFLAGS="$save_CFLAGS"
             LIBS="$save_LIBS"
@@ -38939,11 +39005,7 @@ fi
 
     case ${BAKEFILE_HOST} in
         *-hp-hpux* )
-<<<<<<< aclocal.m4
-            INSTALL_DIR="mkdir"
-=======
                                     INSTALL_DIR="mkdir -p"
->>>>>>> 1.69
             ;;
         *)  INSTALL_DIR="$INSTALL -d"
             ;;
