reverted previous change (except for tiny part that actually made sense)
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/trunk@24823 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9736,6 +9736,7 @@ if test "$wxUSE_WINE" = "yes"; then
     DEFAULT_DEFAULT_wxUSE_GTK=0
     DEFAULT_DEFAULT_wxUSE_MOTIF=0
     DEFAULT_DEFAULT_wxUSE_MSW=1
+    wxUSE_SHARED=no
 fi
 
 if test "$wxUSE_GUI" = "yes"; then
@@ -26543,6 +26544,48 @@ if test "$wxUSE_ZLIB" = "builtin" ; then
     ALL_OBJECTS="${ALL_OBJECTS} \$(ZLIBOBJS)"
 fi
 
+if test "$wxUSE_DISPLAY" = "yes"; then
+    if test "$wxUSE_UNIX" = "yes" -a "$wxUSE_MAC" != 1; then
+        echo "$as_me:$LINENO: checking for Xinerama" >&5
+echo $ECHO_N "checking for Xinerama... $ECHO_C" >&6
+
+ac_find_libraries=
+for ac_dir in $SEARCH_LIB /usr/lib;
+  do
+    for ac_extension in a so sl dylib; do
+      if test -f "$ac_dir/libXinerama.$ac_extension"; then
+        ac_find_libraries=$ac_dir
+        break 2
+      fi
+    done
+  done
+
+        if test "$ac_find_libraries" != "" ; then
+
+  echo "$LDFLAGS" | grep "\-L$ac_find_libraries" > /dev/null
+  result=$?
+  if test $result = 0; then
+    ac_path_to_link=""
+  else
+    ac_path_to_link=" -L$ac_find_libraries"
+  fi
+
+            if test "$ac_path_to_link" != " -L/usr/lib" ; then
+                LDFLAGS="$LDFLAGS $ac_path_to_link"
+            fi
+            GUI_TK_LIBRARY="$GUI_TK_LIBRARY -lXinerama"
+            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+        else
+            echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+            { echo "$as_me:$LINENO: WARNING: \"*** Xinerama not found; disabling wxDisplay\"" >&5
+echo "$as_me: WARNING: \"*** Xinerama not found; disabling wxDisplay\"" >&2;}
+            wxUSE_DISPLAY="no"
+        fi
+    fi
+fi
+
 
 USE_OPENGL=0
 if test "$wxUSE_OPENGL" = "yes"; then
@@ -37460,7 +37503,7 @@ while test \${#} -gt 0; do
         shift
         ;;
 
-       -l*|-L*|-flat_namespace)
+       -l*|-L*|-flat_namespace|-headerpad_max_install_names)
         # collect these options
         args="\${args} \${1}"
         ;;
@@ -37862,6 +37905,8 @@ fi
 
         ;;
     esac
+
+
 
 
 
