Install the config files for cross debs under /usr/$(host), but link them to the default system location under /usr.  This way the commands: wx-config --prefix=/usr/$(host) and wx-config --prefix=/usr --host=$(host) are much more congruent in their action.
Another nail in the coffin for inplace hacks.  Link $srcdir/include to
the build dir so that --prefix=$build_dir really does point to a
realistic looking installed development environment.  I don't know why
I didn't do this instead of (ab)using --exec-prefix to 'fix' this
simple omission for so long.  Probably because it is much more obvious
if contrib is out of the picture.  That makes it a little more work
right now, but long term this is a very clean and correct thing to do.
It completely absolves us of the two independent variables problem,
and of the tree becoming bogus without actually being stale.


git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/trunk@29260 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/wx-config-inplace.in b/wx-config-inplace.in
--- a/wx-config-inplace.in
+++ b/wx-config-inplace.in
@@ -10,23 +10,17 @@
 # Licence:     wxWindows licence
 ############################################################################
 
-# Not much to do here.  Just initialise some variables to point things
-# into the local tree by default and then source the real wx-config if
-# it all still looks sane.  It typically should be if you got this far.
+# Not much to do here.  Just initialise prefix to point things into the
+# local tree by default and then source the real wx-config if it all still
+# looks sane.
 
-check_dirname()
-{
-    if [ ! -d "$1" ]; then
-        printf "\n  *** Error: Directory '$1'\n"    1>&2
-        printf "             no longer exists.\n\n" 1>&2
-        exit 1
-    fi
-    ( cd $1 && pwd )
-}
+this_prefix=$( cd "@abs_top_builddir@" 2> /dev/null && pwd )
 
-this_prefix=$(check_dirname "@abs_top_srcdir@")         || exit
-this_exec_prefix=$(check_dirname "@abs_top_builddir@")  || exit
-flag_option_inplace=yes
+if [ -z "$this_prefix" ]; then
+    printf "\n  *** Error: Directory '@abs_top_builddir@'\n" 1>&2
+    printf "             no longer exists.\n\n"              1>&2
+    exit 1
+fi
 
-. "$this_exec_prefix/lib/wx/config/@TOOLCHAIN_FULLNAME@"
+. "$this_prefix/lib/wx/config/@TOOLCHAIN_FULLNAME@"
 
