introduced wxICON_DEFAULT_TYPE and wxBITMAP_DEFAULT_TYPE; documented these default argument values; matched the wxBitmap and wxIcon interfaces to their real implementations; revised icon.h interface header
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/trunk@55777 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/utils/ifacecheck/rungccxml.sh.in b/utils/ifacecheck/rungccxml.sh.in
--- a/utils/ifacecheck/rungccxml.sh.in
+++ b/utils/ifacecheck/rungccxml.sh.in
@@ -74,6 +74,19 @@ fi
 # can be passed to ifacecheck to aid the comparison
 echo "Running gccxml's preprocessor on the $allheaders file... results in $preprocoutput"
 gccxml -E -dM $flags >$preprocoutput
+if [[ $? != 0 ]]; then
+    echo "Errors running gccxml preprocessor... aborting."
+    exit
+fi
+
+# FIX for IFACECHECK
+# ==================
+
+# these fixes are needed to avoid false warnings/errors by ifacecheck
+
+if [[ "@TOOLKIT@" == "GTK" ]]; then
+    sed -i -e 's/default="wxBITMAP_TYPE_XPM"/default="wxBITMAP_DEFAULT_TYPE"/g' $gccxmloutput
+fi
 
 # cleanup
 rm $allheaders
