refuse to run if not executed by the main configure script
git-svn-id: https://svn.wxwidgets.org/svn/wx/wxWidgets/trunk@15604 c3d73ce0-8a6f-49c7-b76d-6d57e0e08775

diff --git a/samples/configure b/samples/configure
--- a/samples/configure
+++ b/samples/configure
@@ -523,6 +523,10 @@ fi
 
 
 
+if test "x$wx_cv_path_samplesubdirs" = "x"; then
+    { echo "configure: error: Please run configure from the top level directory." 1>&2; exit 1; }
+fi
+
 SAMPLES_SUBDIRS=$wx_cv_path_samplesubdirs
 
 
