Run Ubuntu 20.04 CI build using clang in a container
Ubuntu 20.04 will be dropped by GitHub Actions soon, so we can't use it
any more, but switching this build to a newer Ubuntu version doesn't
work because of #25168, so keep running it under 20.04 but use a
container for it.

Fix some check for matrix.container to really test that we're not using
Ubuntu 18.04 container (which is incompatible with the Node.JS version
used by GitHub Actions) instead of testing that we use some container.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -101,7 +101,8 @@ jobs:
             configure_flags: --enable-compat30
             use_xvfb: true
           - name: Ubuntu 20.04 wxGTK 3 with clang
-            runner: ubuntu-20.04
+            runner: ubuntu-latest
+            container: ubuntu:20.04
             compiler: clang++-10
             configure_flags: --disable-sys-libs
             use_xvfb: true
@@ -165,12 +166,30 @@ jobs:
               fi
 
               compiler=${{ matrix.compiler }}
+              case "$compiler" in
+                clang++*)
+                  compiler_packages='clang libc++-dev libc++abi-dev'
+                  ;;
+
+                g++*)
+                  compiler_packages="${compiler}"
+                  ;;
+
+                '')
+                  # Assume gcc.
+                  compiler_packages='g++'
+                  ;;
+
+                *)
+                  echo '::error ::Unknown compiler kind.'
+                  exit 1
+              esac
 
               # Explanation for installing some less obvious packages:
               #   - coreutils contains nproc used in proc_count.sh called below.
               #   - xvfb is used for running the GUI tests.
               apt-get update -qq
-              apt-get install -qq coreutils ${compiler-g++} git make pkg-config sudo xvfb
+              apt-get install -qq coreutils ${compiler_packages} git make pkg-config sudo xvfb
 
               # Checkout action doesn't work under Ubuntu 18.04 any more, so
               # run checkout manually.
@@ -198,13 +217,13 @@ jobs:
           esac
 
       - name: Checkout
-        if: matrix.container == ''
+        if: matrix.container != 'ubuntu:18.04'
         uses: actions/checkout@v4
         with:
           submodules: 'recursive'
 
       - name: Install CCache
-        if: matrix.container == ''
+        if: matrix.container != 'ubuntu:18.04'
         uses: hendrikmuhs/ccache-action@v1.2.12
         with:
           key: ${{ matrix.name }}
@@ -228,6 +247,8 @@ jobs:
               echo LD=$compiler >> $GITHUB_ENV
 
               allow_warn_opt="-Wno-error=#warnings"
+
+              export WX_EXTRA_PACKAGES="libc++-dev"
               ;;
 
             g++*)
@@ -345,7 +366,7 @@ jobs:
         if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_tests }}
 
       - name: Setup Go
-        if: matrix.container == ''
+        if: matrix.container != 'ubuntu:18.04'
         uses: actions/setup-go@v5
         with:
           go-version: '1'
