Temporary workaround for wxComboBox::ProcessEnter test failure

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -208,7 +208,10 @@ jobs:
           ulimit -c unlimited
           # Running all tests at once fails, apparently due to running out of
           # memory when using ASAN, so split them in 2 parts.
-          /bin/bash -o pipefail -c 'xvfb-run -a -s "-screen 0 1600x1200x24" ./test_gui -d 1  wx* ~[.] 2>&1 | tee -a test_gui.out' || rc=$?
+          # As a temporary workaround, run ButtonTestCase before running wx*
+          # tests because wxComboBox::ProcessEnter test fails without it for
+          # some mysterious reason.
+          /bin/bash -o pipefail -c 'xvfb-run -a -s "-screen 0 1600x1200x24" ./test_gui -d 1 ButtonTestCase,wx* ~[.] 2>&1 | tee -a test_gui.out' || rc=$?
           /bin/bash -o pipefail -c 'xvfb-run -a -s "-screen 0 1600x1200x24" ./test_gui -d 1 ~wx* ~[.] 2>&1 | tee -a test_gui.out' || rc=$?
           if [ -n "$rc" ]; then
             if fgrep -q '(core dumped)' test_gui.out; then
