Try better workaround for the ASAN CI build failures
Try excluding RichTextCtrlTestCase in the CI build using ASAN, as the
test can still be killed while running the Table sub-test of this test
case even when running only a subset of all tests, so try skipping this
one instead.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -257,17 +257,14 @@ jobs:
                 ASAN_OPTIONS=detect_leaks=0
             fi
             export ASAN_OPTIONS="$ASAN_OPTIONS fast_unwind_on_malloc=0"
+
+            # Running all tests at once fails, apparently due to running out of
+            # memory when using ASAN, work around this problem by excluding
+            # RichTextCtrlTestCase whose Table sub-test seems to be problematic.
+            wx_tests_selection='~[.] ~RichTextCtrlTestCase'
           fi
           ulimit -c unlimited
-          # Running all tests at once fails, apparently due to running out of
-          # memory when using ASAN, work around this problem by splitting them
-          # in 2 parts.
-          #
-          # Also, as a temporary workaround for a problem with ProcessEnter()
-          # test, run ButtonTestCase before running wx* tests. This should be
-          # reverted once the actual problem in the test is fixed.
-          /bin/bash -o pipefail -c 'xvfb-run -a -s "-screen 0 1600x1200x24" ./test_gui -d 1 ButtonTestCase,wx* ~[.] 2>&1 | tee -a test_gui.out' || rc=$?
-          /bin/bash -o pipefail -c 'xvfb-run -a -s "-screen 0 1600x1200x24" ./test_gui -d 1 ~wx* ~[.] 2>&1 | tee -a test_gui.out' || rc=$?
+          /bin/bash -o pipefail -c "xvfb-run -a -s '-screen 0 1600x1200x24' ./test_gui -d 1 $wx_tests_selection 2>&1 | tee -a test_gui.out" || rc=$?
           if [ -n "$rc" ]; then
             if fgrep -q '(core dumped)' test_gui.out; then
                 echo '*** Test crashed, trying to get more information ***'
