Enable use of libcurl and test it using local httpbin instance
Libcurl was implicitly disabled by --disable-sys-libs, so enable it
explicitly to still use it.

Also install httpbin using pip to use it for wxWebRequest tests.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,7 +19,7 @@ jobs:
           - name: wxGTK Ubuntu 20.04 with ASAN
             runner: ubuntu-20.04
             compiler: gcc
-            configure_flags: --disable-compat30 --disable-sys-libs
+            configure_flags: --disable-compat30 --disable-sys-libs --with-libcurl
             gtk_version: 3
             skip_samples: true
             use_asan: true
@@ -119,13 +119,27 @@ jobs:
           fi
           make -k -C tests $wxBUILD_ARGS "CXXFLAGS=$wxMAKEFILE_CXXFLAGS" "LDFLAGS=$wxMAKEFILE_LDFLAGS"
 
+      - name: Launching httpbin
+        if: matrix.skip_testing != true
+        run: |
+          pip install httpbin
+          python -m httpbin.core 2>&1 >httpbin.log &
+          echo 'WX_TEST_WEBREQUEST_URL=http://localhost:5000' >> $GITHUB_ENV
+
       - name: Testing
         if: matrix.skip_testing != true
         run: |
           echo 'Testing...'
           pushd tests
-          ./test
+          ./test || rc=$?
           popd
+          if [ -n "$rc" ]; then
+            echo '*** Tests failed, contents of httpbin.log follows: ***'
+            echo '-----------------------------------------------------------'
+            cat httpbin.log
+            echo '-----------------------------------------------------------'
+            exit $rc
+          fi
 
       - name: Testing GUI using Xvfb
         if: matrix.skip_testing != true && matrix.skip_gui != true && matrix.use_xvfb
