Skip tests that currently fail under wxMac

diff --git a/.github/workflows/ci_mac.yml b/.github/workflows/ci_mac.yml
--- a/.github/workflows/ci_mac.yml
+++ b/.github/workflows/ci_mac.yml
@@ -204,8 +204,10 @@ jobs:
       working-directory: tests
       run: |
         export ASAN_OPTIONS=fast_unwind_on_malloc=0
+        # Exclude tests that are currently known to fail
+        wx_tests_selection='~[valnum] ~wxPersistTLW ~wxPersistDVC ~wxTopLevel::Show ~wxFont::Weight ~wxFont::NativeFontInfo ~WebView ~RadioButton::Single ~RadioButton::Focus ~wxHtmlPrintout::Pagination ~ChoiceTestCase ~ComboBoxTestCase ~CheckListBoxTestCase ~ListBoxTestCase ~RearrangeListTestCase ~wxTextCtrl::GetBestSize ~TextCtrlTestCase ~ClippingBoxTestCase::wxClientDC ~wxExecute::RedirectUTF8 ~Ellipsization::NormalCase ~SpinCtrl::* ~SpinCtrlDouble::* ~NotebookTestCase ~SettingsTestCase ~XRC::LoadURL ~Window::Show ~Window::SizerErrors ~ModalDialogsTestCase ~Button::Click ~Button::Disabled ~wxDVC::GetItemRect ~wxDVC::AppendTextColumn ~Grid::KeyboardSelection ~Grid::CellClick ~Grid::ReorderedColumnsCellClick ~Grid::CellSelect ~wxStyledTextCtrl::AutoComp ~EvtLoopTestCase ~EventPropagationTestCase'
         # Explicitly use bash because /bin/sh doesn't have pipefail option
-        /bin/bash -o pipefail -c "./test_gui"
+        /bin/bash -o pipefail -c "./test_gui $wx_tests_selection"
 
     - name: Building samples
       if: matrix.skip_testing != true && matrix.skip_samples != true
